version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"

  client:
    build: 
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules 
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]
  authservices:
    build:
      context: ./authServices
    volumes:
      - ./authServices:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - postgres
    ports:
      - "3001:3001"
